switch none deployment strategy to basic
Azure/k8s-deploy pull request #204
Opened 2022-06-27 17:20 UTC by davidgamero

ref #174

2022-06-27 20:04 UTC, OliverMKing requested changes

2022-06-27 20:04 UTC, OliverMKing commented on action.yml
>        required: false
There's also logic in the codebase that relies on the value of strategy with a switch statement. that should be modified away from fall through default logic.

2022-06-27 20:42 UTC, jaiveerk approved these changes

2022-06-27 22:22 UTC, davidgamero commented on action.yml
>        required: false
swapped

2022-06-27 22:23 UTC, davidgamero commented
changed it to only throw a warning for unrecognized strategies instead of running the basic one

2022-06-28 19:24 UTC, OliverMKing requested changes

2022-06-28 19:24 UTC, OliverMKing commented on README.md
> +    Default value: basic<br>Deployment strategy to be used while applying manifest files on the cluster.<br>basic - Template is force applied to all pods when deploying to cluster.<br>canary - Canary
add that it's required here too

2022-06-28 19:30 UTC, davidgamero commented on src/strategyHelpers/deploymentHelper.ts
> +         core.warning('Deployment strategy is not recognized.')
fixed

2022-06-28 19:37 UTC, OliverMKing commented on action.yml
> +      description: 'Deployment strategy to be used. Allowed values are basic, canary and blue-green'
maybe specify that basic only works for deploy action

2022-06-28 19:39 UTC, OliverMKing approved these changes

2022-06-28 20:33 UTC, merged