Added Traffic split annotations
Azure/k8s-deploy pull request #215
Opened 2022-07-12 04:21 UTC by Vidya2606

2022-07-12 14:22 UTC, OliverMKing requested changes

2022-07-12 14:22 UTC, OliverMKing commented on src/strategyHelpers/blueGreen/smiBlueGreenHelper.ts
> +   annotations: {[key: string]: string} = {}
how are you letting a user pass this in? You need to add logic to let a user insert it.

We also need to do the same thing for canary.

2022-07-18 16:18 UTC, OliverMKing commented on src/run.ts
> +   const annotations: {[key: string]: string} = {}
you aren't passing in the annotations with core.getInput

2022-07-19 14:29 UTC, OliverMKing requested changes

2022-07-19 14:29 UTC, OliverMKing commented on action.yml
> +      default: 0
why a default of 0?

2022-07-19 14:29 UTC, OliverMKing commented on src/run.ts
>           break
you likely need to add this to the deploy scenario as well

2022-07-19 14:29 UTC, OliverMKing commented on src/run.ts
> +   const annotations: {[key: string]: string} = {}
also keep in mind that with core.getInput you will be parsing it as a string. You will have to parse it as an object

2022-07-22 15:02 UTC, OliverMKing requested changes
Looking good! Small doc changes then we should be good.

2022-07-22 15:02 UTC, OliverMKing commented on action.yml
> +      description: 'Traffic split annotations in the form of key/value pair can be used'
Also mention that it's relevant only if strategy == canary or blue green

2022-07-22 21:05 UTC, davidgamero commented on src/strategyHelpers/deploymentHelper.ts
> +   annotaions: {[key: string]: string} = {}
nit: typo annotaions -> annotations

2022-07-22 21:05 UTC, davidgamero commented on src/strategyHelpers/blueGreen/smiBlueGreenHelper.ts
> +   annotaions: {[key: string]: string} = {}
nit: typo

2022-07-25 17:39 UTC, OliverMKing approved these changes

2022-07-25 17:39 UTC, davidgamero approved these changes

2022-07-25 17:43 UTC, merged