Fixing Ubuntu Runner Version
Azure/k8s-deploy pull request #259
Opened 2022-11-22 18:39 UTC by jaiveerk

Fixing ubuntu runner version to 20 since latest gives an OS that is not compatible with an action used in our integration tests.

2022-11-22 18:41 UTC, OliverMKing commented
It would be better to change the action rather than the runner. We need to be sure that our actions work with the latest runner.

2022-11-22 18:42 UTC, OliverMKing requested changes
^

2022-11-22 20:41 UTC, OliverMKing approved these changes

2022-11-23 13:38 UTC, elenavillamil approved these changes

2022-11-23 14:25 UTC, merged