Check for error from Azure when using the private-cluster feature
Azure/k8s-deploy pull request #270
Opened 2022-12-07 14:09 UTC by oddsund

Move the error check for Azure earlier, so that a well defined error is thrown on error instead of a JSONSyntax error.

The issue is that when Azure returns an error, like when there's an issue with the access to the principal used. When this happens, the stdout field will be an empty string, and the error message will be set to a non-json string.

2022-12-07 14:12 UTC, oddsund commented
@microsoft-github-policy-service agree

2022-12-07 14:12 UTC, oddsund commented
@microsoft-github-policy-service agree

2022-12-08 17:32 UTC, jaiveerk submitted a review, later dismissed

2022-12-12 14:47 UTC, OliverMKing requested changes

2022-12-12 14:47 UTC, OliverMKing commented on src/types/privatekubectl.ts
> +      if (runOutput.exitCode !== 0) {
This part looks good to me and makes sense so we don't fail on json parsing like you said.

2022-12-12 14:47 UTC, OliverMKing commented on src/types/privatekubectl.ts
> -      if (runOutput.exitCode !== 0 && runObj.exitCode !== 0) {
We need to keep this part here
```TypeScript
if (runOutput.exitcode !== 0) {
         throw Error(`failed private cluster Kubectl command: ${kubectlCmd}`)
}
```

Without this we won't behave exactly like the [overridden method](https://github.com/Azure/k8s-deploy/blob/e3e5e845b7c25d360b46bd6115c23e2f52a5ed9a/src/types/kubectl.ts#L173). `getExecOutput` will [throw if the exit code is none zero](https://github.com/actions/toolkit/blob/main/packages/exec/src/interfaces.ts#L28) so we need to replicate that behavior here.

2023-01-03 14:56 UTC, OliverMKing approved these changes

2023-01-03 14:58 UTC, OliverMKing commented on src/types/privatekubectl.ts
> -      if (runOutput.exitCode !== 0 && runObj.exitCode !== 0) {
Looks good to me! I'll squash merge it when we merge into main. Thanks!

2023-01-03 15:05 UTC, davidgamero approved these changes
Lgtm

2023-01-03 15:09 UTC, OliverMKing commented
Going to squash and merge this. Will kick off a release sometime soon.

2023-01-03 15:09 UTC, merged